script: "export JRUBY_OPTS='-X+O -J-Djruby.launch.inproc=false -J-Xmx1024m -J-XX:MaxPermSize=2048m' bundle exec rspec"
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0
  - 2.2.4
  - jruby-9.0.4.0
matrix:
  include:
    - rvm: 2.3.0
      script: "bundle exec rubocop"
      env: "RUBOCOP=true"